### ISSUE TITLE
Wrong image paths

### ISSUE THREAD

**Issue by MartinKavik** [halfzebra/create-elm-app#136]
Hi!

I've just upgraded from **create-elm-app** version **0.6.0** to **0.8.1** and `elm-app build` started to generate wrong image paths.

## Example
**`/src/main.css`**:
```css
body {
  background-image: url(image/background-pic.jpg);
}
```
**`/dist/css/main.559813e7.css`** after `elm-app build`:
```css
body{background-image:url(./static/media/background-pic.947ee9b2.jpg);}
```
## Problem
The correct image path should be `/static/media/background-pic.947ee9b2.jpg`
(without the dot before `/static`)

Thank you very much for this package and fix or some info, how can I fix it by myself.
